name: WarpDrive
main: no.runsafe.warpdrive.WarpDrive
version: 1.1.@BUILD@
authors: [Kruithne, mortenn]
description: Public and private warps for minecraft
commands:
  sethome:
    description: Set private warp location
  delhome:
    description: Remove a private warp location
  home:
    description: Teleport to a private warp location
  homeother:
    description: Teleport to another players homes.
    aliases: [ho]
  setwarp:
    description: Set public warp location
  delwarp:
    description: Remove a private warp location
  warp:
    description: Teleport to a private warp location
  top:
    description: Teleports the player to the top block of his or her x/z coordinate.
  teleportpos:
    description: Teleports to a given coordinate
    aliases: [tppos]
  teleport:
    description: Teleports you to another player
    aliases: [tp]
  wipehomes:
    description: Deletes all homes in a world
  teleporttoentityid:
    description: Teleports you to the location of an entity
    aliases: [etp]
  smartwarp:
    description: Create a smart warp for a world and start scanning it for locations
  rescansmartwarp:
    description: Rescans a smart warp for a world.
  setportal:
    description: Allows setting/editing of portals in-game.
    aliases: [setp]
  setregionportal:
    description: Allows setting/editing of region-based portals in-game.
    aliases: [setrp]
  delregionportal:
    description: Deletes a region-based portal.
    aliases: [delrp]
  setzone:
    description: Allows setting your current zone.